### ISSUE TITLE
Merge "labeling" code from forcefield_labeler back into ForceField class now that XML is retained

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/smarty#105]
It appears that a bunch of code from `forcefield.py` was just copied into `forcefield_labeler.py` and modified a bit. This creates a huge technical debt nightmare.

We can't keep this. We need to do one of the following:
- Someone needs to take complete responsibility is it to keep the code in `forcefield_labeler.py`  completely current with `forcefield.py`.
- We integrate its functionality into `forcefield.py` in a minimally invasive way.
- We delete `forcefield_labeler.py` if it no longer serves a purpose.

Otherwise, the technical debt of maintaining two nearly-identical pieces of code is enormous, and we can't spare the effort on this.

**Comment by davidlmobley** [comment]
@jchodera - this was me, but I agree. I'm tied up today and will respond in more detail early in the week, but until `ForceField` retained XML, I couldn't see how to integrate the functionality into `forcefield.py`. I believe I can see how to do so now, so I should be able to do that.  

(My original plan had been to take complete responsibility to keep it current until we figured out a better way of doing things, but I didn't want to bother you with helping me figure that out until the parameter sampler was in place since that was a true bottleneck where we can't proceed without you.)

**Comment by jchodera** [comment]
Sounds good---thanks!

**Comment by davidlmobley** [comment]
I don't think I have anything important to say I didn't summarize above. I'll be endeavoring to fix this by re-merging the forcefield labeler with the forcefield class itself now that the XML is retained.

However, a brief overview of the history might help understand why this ended up this way to begin with. We discussed, in one of our calls, need a tool which would specify which parameters were applied to which atoms in which molecules, and you said the best way to do it at this point was to make a class structure which mirrored `ForceField` but provided access to the info I needed (this was also important because at the time, `ForceField` discarded the XML, and no information on what parameters are used is retained in OpenMM we discussed here https://github.com/open-forcefield-group/smarty/issues/66 ). At the time this posed a bottleneck for both Bryce in Michael's group and for two people on my end, so I had to do something about it. 

As I was coding it up, I realized that it was going to be really bad for sustainability to have two pieces of code doing effectively the same thing, so I made a note to bring it up with you later -- but since we were able to proceed with the "hack of a solution" I came up with here, I wanted to wait until after you had property estimator in place (which is currently a bottleneck) before coming up with a more general plan. And now that `ForceField` retains the XML, this makes things much easier.

Obviously, if I'd just realized originally that the easy solution was to just extend `ForceField` to retain the XML, that would have made things a lot simpler. :)  Sorry about that.

**In any case, I'll fix this in the near future.**

**Comment by davidlmobley** [comment]
Resolved by #113 .

Note that new generators now also need a `parseForce` function which takes an OEMol and parses out what force terms/parameters would be applied to that molecule, returning details. If new generators are added, it should be straightforward to adapt existing parsers to cover new generators.
