### ISSUE TITLE
Implementing Hierarchy Tracking

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#34]
We would like a way to track hierarchy (parents and children) so we can make tree diagrams and track how smarty is making changes. 

My plan currently is to create a dictionary which will track a list of children for each parent. 

@davidlmobley and I discussed creating objects for chemical environments. However, we are concerned that this would have to be completely redone when we move to sampling bonds, angles, and torsions.

**Comment by jchodera** [comment]
Currently, we track a tuple of `(smarts, typename)`. What about just extending this to `(smarts, typename, parent)`?

**Comment by jchodera** [comment]
From that information, you can completely reconstruct the (directed) graph of which types gave rise to which children (since we cannot eliminate parent types).

**Comment by davidlmobley** [comment]
@jchodera : Is there a strong reason to prefer that approach over just providing lookup of parent `(smarts, typename)` via something like a `parents` dictionary? Extending the tuple would require much more extensive code changes as everything which handles a two-element tuple would need modification, whereas if we just have look-up when needed via a dictionary code changes will be isolated.

We figured we could use this dictionary approach for now, since down the line (when we move to bonds, angles, and torsions) we'll need more extensive rewrites anyway and that would be a good time to extend to a more general notion of chemical environment/parent tracking.

**Comment by jchodera** [comment]
I don't think you save much in going the dict approach, since you need to modify the dict and pass it around in the sample places as the tuple, but go ahead and give it a try!

**Comment by bannanc** [comment]
I'm looking through the code again, I've only interacted with a few parts of the sampler. If we're going to have to pass the dictionary around then it defeats the point of introducing it.

**Comment by davidlmobley** [comment]
I think there's quite a bit of the code which interacts with types without modifying them or needing to know about parents/children, i.e. things printing type statistics, the part which actually does the type matching, and so on. But yeah, @bannanc can sort that out.

**Comment by jchodera** [comment]
>  If we're going to have to pass the dictionary around then it defeats the point of introducing it.

That's what I was thinking.  But I'm not sure what is easiest.

**Comment by davidlmobley** [comment]
Closed by #35
