### ISSUE TITLE
Decide where Smirff belongs / what goes where

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#40]
Right now the overall organization of `open-forcefield-group` doesn't seem particularly intuitive to me, so we'll have to think a bit more carefully about what belongs where. For example, right now we have the `ffxml` SMIRFF forcefield implementation in the `smarty` repository, which is perhaps odd. Should we be moving that to `open-forcefield-tools`? And would that be where we'd be putting property estimator and so on?

**Comment by jchodera** [comment]
I put the forcefield parameterization tool in smarty for now since we can keep SMARTS typing related tools together for the moment. We can import these tools with "from smarty.forcefield import ForceField" for the short term.

Do we want a better name than open-forcefield-tools for the ThermoML property calculation framework? Dashes aren't allowed in module names anyway, and I'm not sure we want to write "from open_forcefield_tools import .. "

**Comment by davidlmobley** [comment]
> I put the forcefield parameterization tool in smarty for now since we can keep SMARTS typing related tools together for the moment. We can import these tools with "from smarty.forcefield import ForceField" for the short term.

Sounds fine for now.

> Do we want a better name than open-forcefield-tools for the ThermoML property calculation framework? Dashes aren't allowed in module names anyway, and I'm not sure we want to write "from open_forcefield_tools import .. "

I agree this is cumbersome. Right now we've got SMIRFF for the forcefield, Smarty for the atom type sampler... Something starting with S? ;) Or maybe smirff_param, for "SMIRFF parameterization tools"...? Brilliant ideas don't seem to be coming to me right now.

**Comment by jchodera** [comment]
We could call the ThermoML property calculation framework `thermomix` since it computes thermodynamic properties of mixtures (and is also [a blender that cooks](https://en.wikipedia.org/wiki/Thermomix)).

We can move the forcefield stuff over to a new `smirff` repo eventually, but there is some nontrivial overhead associated with setting up and maintaining each repo, so maybe we want to think of something more general we can dump much of this stuff into.
- `gbff` (General Bayesian Force Field) might work
- `openforcefield` might be fine for many of these tools, and be a bit more descriptive

**Comment by davidlmobley** [comment]
I like "openforcefield" for most of it down the road. If you want thermomix
for the property calculation framework in the shorter term that's fine too.

Agreed regarding the overhead.

DM

On Mon, Jul 4, 2016 at 8:15 AM, John Chodera notifications@github.com
wrote:

> We could call the ThermoML property calculation framework thermomix since
> it computes thermodynamic properties of mixtures (and is also a blender
> that cooks https://en.wikipedia.org/wiki/Thermomix).
> 
> We can move the forcefield stuff over to a new smirff repo eventually,
> but there is some nontrivial overhead associated with setting up and
> maintaining each repo, so maybe we want to think of something more general
> we can dump much of this stuff into.
> - gbff (General Bayesian Force Field) might work
> - openforcefield might be fine for many of these tools, and be a bit
>   more descriptive
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/open-forcefield-group/smarty/issues/40#issuecomment-230311904,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGzUYfnTgxILAFKWIq-Jjku1wfLrz75yks5qSSN_gaJpZM4JECTT
> .

## 

David Mobley
dmobley@gmail.com
949-385-2436

**Comment by jchodera** [comment]
> I like "openforcefield" for most of it down the road. 

I'll go with that for now.
