### ISSUE TITLE
Improved Searching Strategy

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/smarty#50]
We would like to add a structure to allow a more efficient strategy for searching for new atom types. 

This would stop proposing changes to a certain element type if all populations for a base atom type have been found. 

I'm thinking about this as a mini-scoring idea. For example in the case of oxygen, If it finds OH and OS (or two types that at least separate these) then it would stop adding descriptors to atom types that begin with [#8 ...] 

I've self assigned this, but I'm still thinking through implementation so I'm very open to suggestions. I'm going to try to have more details outlined here later tonight.

**Comment by davidlmobley** [comment]
> I'm thinking about this as a mini-scoring idea. For example in the case of oxygen, If it finds OH and OS (or two types that at least separate these) then it would stop adding descriptors to atom types that begin with [#8 ...]

I'm not sure I'd call it scoring, but yes, this is exactly what I was imagining. If I've already found two atom types for carbon (i.e., SMARTS beginning with the characters `[#6`) which have a 1:1 correspondence to the carbon types in my set, then there is no reason to discover further carbon types unless that score drops, since we _already know_ they are going to be rejected. So we should only be proposing moves that focus on non-carbon proposals, or (a small fraction of the time) delete existing carbon types.

**Comment by jchodera** [comment]
Are we sure this is the problem we should be solving right now? I thought we were currently stuck on the problem that the accessible SMARTS strings are not sufficiently large to encompass the whole parm@frosst set. Have we solved that? If so, then we could look at the convergence rates of the current sampler and have a baseline for quantifying how much better proposal strategies accelerate convergence. But I would imagine it premature to tackle something like this until we have solved that problem.

**Comment by davidlmobley** [comment]
@jchodera - this is not the main problem, it's just something we thought of while working through the SMARTS chemistry which will accelerate sampling and (especially right now) debugging. i.e., there's no point sitting there watching Smarty try and elaborate lots of different types of carbon and oxygen if all you're waiting for it to find are some sub-types of hydrogen. 

We basically know the solution to the SMARTS strings problem now and are working on it separately from this. We can discuss it tomorrow.

FYI, it's actually worse than you describe, as the SMARTS strings are still not elaborate enough to include all of AlkEthOH, much less parm@frosst. :)  But, we should have AlkEthOH working (i.e. be able to construct elaborate enough SMARTS strings) very soon.

**Comment by jchodera** [comment]
There are lots of things we can do with efficient sampling strategies. When
we get to the point where we need to try a few things, I'd like to
modularize the proposal code and bring in @maxentile and @pgrinaway to
brainstorm some clever schemes. They have been thinking about this a great
deal.

**Comment by cbayly13** [comment]
Here is a brief supporting explanation to @jchodera @maxentile and @pgrinaway of what we find daunting in terms of sampling:
original smarty decorated [basetypes] to make [basetypes+properties] and [basetypes+properties+substituent[basetype] ]

then we realized we need to sample [basetypes+properties+substituent[basetype+properties] ]

Now we know we need to sample [basetypes+properties+substituent[basetype+properties+1stSecondarySubstituent[basetype+properties]+2ndSecondarySubstituent[basetype+properties]+3rdSecondarySubstituent[basetype+properties] ] ]

it is deeply nested and the sampling space is Very Large. It is not impossible to do this randomly, it is simply daunting. That's why we can't help but wonder how we are going to do this. We agree that it is a higher priority to first get in place the tools to substitute out to beta substituents (two atoms away from the one we are interested in and we are working on it.

**Comment by davidlmobley** [comment]
@jchodera : 

> There are lots of things we can do with efficient sampling strategies. When
> we get to the point where we need to try a few things, I'd like to
> modularize the proposal code and bring in @maxentile and @pgrinaway to
> brainstorm some clever schemes. They have been thinking about this a great
> deal.

Great. Maybe now is a good time to think about that, as we're probably looking at a complete rewrite of much of the code as we shift to chemically-aware smirks proposals (since we are headed to bonds, angles, and torsions eventually anyway, we are going to think through how to do that in the same framework). In other words, we're starting to think through larger changes we'll need, so now is probably also a good time to think through changes to the proposal code.

**Comment by davidlmobley** [comment]
Closed by #55
