### ISSUE TITLE
Fix sporadic failure (key error) introduced in last PR

### ISSUE THREAD

**Issue by davidlmobley** [open-forcefield-group/smarty#56]
It looks like #55 introduced a sporadic Smarty failure, i.e. a key error is possible in some situations but the tests aren't long enough to always catch it - at least that's my take on the error messages (i.e. see https://travis-ci.org/open-forcefield-group/smarty/jobs/143498708 - failures in two out of three cases). 

@bannanc , can you take a look?

Thanks.

**Comment by davidlmobley** [comment]
@bannanc - just wanted to make sure you saw this? 

One suggestion to aid troubleshooting is to make sure to fix the random seed somewhere to allow reproducing the problem.

**Comment by bannanc** [comment]
@davidlmobley I just saw this I'll take a look when I get into the office this morning.

**Comment by bannanc** [comment]
So the tests are still passing locally, but I'm getting a key error when I run with more iterations, I'm investigating now.

**Comment by bannanc** [comment]
@davidlmobley  
I think I've found the problem. I was under the impression we were removing "unused" base types from the self.basetype list, but those are in a separate list self.used_basetypes. 

This means my code was looking for something like chlorine in the atomlist after it had been removed since it is still in basetypes. 

I'm doing some tests to double check, I'll get a pull request up soon.
